export const EXECUTION_LIMIT_MINUTES = 120;
export const EXECUTION_LIMIT_MS = EXECUTION_LIMIT_MINUTES * 60 * 1000;
export const CALL_LIMIT_MINUTES = 30;
export const CALL_LIMIT_MS = CALL_LIMIT_MINUTES * 60 * 1000;
export const MAX_CALLS = 24;
export const MAX_INPUT = 600000;
export const MAX_OUTPUT = 180000;
